name: Robot Tests - invictus-academy-front ğŸ‘·

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    name: Front Tests Invictus
    runs-on: ubuntu-latest

    steps:
      - run: echo "ğŸš€ Clone repository on Invictus Virtual Machine ğŸš€"
      - name: Checkout Repository
        uses: actions/checkout@v4

      - run: echo "ğŸŒ± Install Python v3.12 ğŸŒ±"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: echo "ğŸŒ Install Chromium + Chromedriver ğŸŒ"
      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          which chromium-browser
          which chromedriver

      - run: echo "â• Install Dependencies of Invictu's Project â•"
      - name: Install dependencies
        run: pip install -r requirements.txt

      - run: echo "ğŸ¤– Execute tests Frontend of Invictus ğŸ¤–"
      - name: Run Robot Framework tests
        env:
          CHROME_BIN: /usr/bin/chromium-browser
          CHROMEDRIVER_BIN: /usr/bin/chromedriver
        run: |
          robot --outputdir logs/ tests/

      - run: echo "ğŸ“ Saving logs Tests ğŸ“"
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: logs-tests
          path: logs/
