name: Robot Tests - invictus-academy-front ğŸ‘·
 
on:
  push:
    branches: [main]
 
  pull_request:
    branches: [main]
  workflow_dispatch:
 
jobs:
  test:
    name: Front Tests Invictus
    runs-on: ubuntu-latest
 
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: https://github.com/iamalissontomazelli/invictus-academyt14-front-robot.git
 
    steps:
      - run: echo "ğŸš€ Clone repository on Invictus Virtual Machine ğŸš€"
      - name: Checkout Repository
        uses: actions/checkout@v4
 
      - run: echo "ğŸŒ± Install Python v3.12 ğŸŒ±"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
 
      - run: echo "â• Install Dependencies of Invictu's Project â•"
      - name: Install dependencies
        run: pip install -r requirements.txt
 
      - run: echo "ğŸ¤– Execute tests Frontend of Invictus ğŸ¤–"
      - name: Run Robot Framework tests
        run: robot --outputdir logs/ tests/
 
      - run: echo "ğŸ“ Saving logs Tests ğŸ“"
      - name: Upload Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: logs-tests
          path: logs/